CREATE TABLE employee (
	employee_Id uuid PRIMARY KEY NOT NULL DEFAULT uuid_generate_v4(),
	name VARCHAR(255) NOT NULL,
	job_Role VARCHAR(255) NOT NULL,
	salary NUMERIC(5,2),
	Birth DATE NOT NULL,
	employee_Registration INTERGER NOT NULL
)

CLICAR COM BOTÃO DIREITO EM CIMA DO BANCO, IR ATÉ EXTENCION, PROCURAR 
A EXTECION UUID_OSSP SALVAR.